name:                day5
version:             0.1.0.0
github:              "githubuser/day5"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

description: Stuff

dependencies:
- base >= 4.7 && < 5
- text
- containers

executables:
  day5-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
